---
resources:
- name: github
  icon: github
  type: git
  source:
    uri: https://github.com/david-universal-robots/concourse.git
    username: {{username}}
    password: {{password}}
    branch: master

task-config: &task-config
  platform: linux
  inputs:
    - name: github
  params:
    RAILS_ENV: test
    DATABASE_URL: postgresql://postgres@localhost
  run:
    path: /bin/bash
    args:
      - -c
      - |
        echo "=== Setting up Postgres..."
        apt-get update
        apt-get install -y postgresql libpq-dev cmake nodejs
        cat > /etc/postgresql/*/main/pg_hba.conf <<-EOF
        host   all   postgres   localhost   trust
        EOF
        service postgresql restart
        echo "=== Project requires that we clone rails... "
        cd github
        git clone --mirror https://github.com/rails/rails
        echo "=== Installing Gems..."
        gem install -N bundler
        bundle install
        echo "=== Running Tests..."
        bundle exec rails db:setup
        bundle exec rails test

jobs:
- name: test
  public: true
  plan:
    - get: github
      trigger: true
    - task: run-tests
      config:
        image_resource:
          type: registry-image
          source: { repository: ruby, tag: 2.6.3 }
        << : *task-config
